### ISSUE TITLE
browsersync: reload when content files are edited

### ISSUE THREAD

**Issue by puckey** [brocessing/kirby-webpack#15]
Currently BrowserSync is set up to ignore files in the 'content' directory. If this were to be removed, you would get live updates when the content is edited. I can't see any downsides to it, but maybe I am missing something.

**Comment by pqml** [comment]
Since the panel uses xhr/ajax, we ignored the content directory to avoid complete reloading of the panel when editing. 

The alternative could be to watch the content directory and disable livereloading in the panel by using the `snippetOptions` of browsersync. But livereloading is great when it comes to edit blueprints, widgets, custom fields..

Maybe there is another answer like an option in `main.config.js` to easily switch between ignoring content folder and turn off live reloading for the panel?

**Comment by puckey** [comment]
Ahh, I understand. So editing in the panel causes the content file to change, which causes browsersync to reload the page. If only the callback in the files option would give information about the user's current url – then you could reload conditionally: https://www.browsersync.io/docs/options#option-files

**Comment by pqml** [comment]
@puckey, I think it's ok!

I dug into browsersync to find if we can make custom events to pass custom messages between the client and the devServer. I found the perfect answer: https://github.com/BrowserSync/browser-sync/issues/662#issuecomment-110478137

Now, browsersync send a special `kirby:contentupdate` when a file inside the `/www/content` is updated. Client-side, a browsersync plugin check if the user is in the panel and if not, it will reload the page.

The update is available from [the latest release](https://github.com/brocessing/kirby-webpack/releases/tag/0.6.2)

**Comment by puckey** [comment]
Very cool - thanks Hugo!
