### ISSUE TITLE
Kirby Package Manager and gitignore

### ISSUE THREAD

**Issue by illycz** [brocessing/kirby-webpack#34]
Would it be possible to add plugins to .gitignore configurable?
I don't think everyone is using CI.

What do you think?

**Comment by pqml** [comment]
Not sure to understand what you want

A lot of features are missing from Kirby Package Manager
- We really need to add some kind of version control (possibly based on git hash because a lot of kirby plugins don't make releases or don't update package.json version number)
- We also needs an `unlink` feature to simply download the plugin without put it in the .gitignore. I have to do this manually on some project using CI to avoid breaking the project if a plugin makes breaking changes

We made a repo to move kirby package manager outside the kirby webpack boilerplate but didn't start to work on it
https://github.com/brocessing/kirby-package-manager

**Comment by illycz** [comment]
I meant the option to cancel adding plugin to .gitignore when I use Kirby Package Manager...

**Comment by arnaudjuracek** [comment]
So what you're proposing is something along the line of `npm run kirby:add --no-gitignore` ?

**Comment by illycz** [comment]
Yes or Kirby option in config file...

**Comment by arnaudjuracek** [comment]
Commit 72a4e07a0edba408cbeaebbcedd979a045f2613e adds the `--no-ignore` flag to `kirby:add`

Upgrade to [`0.7.3`](https://github.com/brocessing/kirby-webpack/releases/tag/0.7.3) to be able to run : 
```sh
$ yarn kirby:add --no-ignore
$ npm run kirby:add -- --no-ignore
```
