### ISSUE TITLE
Problem running on Ubuntu 16.04

### ISSUE THREAD

**Issue by knaggit** [brocessing/kirby-webpack#37]
Hello everyone,
I've tried to install kirby-webpack on my local Ubuntu 16.04 with following setup:
PHP 7.2.2
node.js 7.10.1
npm 4.20

I get the following error message:
`$ npm run start        `  
`> corp_web@0.0.1 start /home/xxx/`
`> node scripts/check-preprocessor.js && cross-env NODE_ENV=development node scripts/webpack-serve.js`

`[1/3] Starting a php server...`
`PHP Server started on localhost:35410`

`⚠️  Warning: `
`Node can't reach PHP built-in server through localhost.`
`Proxying [::1]:35410 instead.`

`[2/3] Running the webpack compiler...`
`webpack building...`
`webpack built 932b8f65491bcf8c154b in -9949ms`
`ℹ ｢wdm｣: Version: webpack 3.11.0`
`            Asset    Size  Chunks                    Chunk Names`
`assets/bundle.css  292 kB       0  [emitted]  [big]  assets/bundle.css`
` assets/bundle.js  244 kB       1  [emitted]         assets/bundle.js`
`ℹ ｢wdm｣: Compiled successfully.`

`[3/3] Starting the browser-sync server...`
`[Browsersync] Proxying: http://[::1]:35410`
`[Browsersync] Access URLs:`
 `--------------------------------------`
`       Local: http://localhost:8081`
`    External: http://x.x.x.x:8081`
` --------------------------------------`
`          UI: http://localhost:3001`
` UI External: http://x.x.x.x:3001`
 `--------------------------------------`
`[Browsersync] Watching files...`

`✔︎  Success: kirby-webpack server is up and running`

Ports aren't in use through other services. Anyone have these problems to or someone can give me a hint?

**Comment by pqml** [comment]
```

**Comment by pqml** [comment]
`⚠️ Warning:
Node can't reach PHP built-in server through localhost.
Proxying [::1]:35410 instead.`

This is not an error; it's just a warning which is always displayed.
On OSX (don't know about other OS), the PHP built-in server only support IPv6 when serving on `localhost`. So we need to proxying from ipv6 `[::1]` instead of localhost. 

More infos here: http://php.net/manual/en/features.commandline.webserver.php#120449

I can surely disable this behaviour for Window and Linux in future releases

**Comment by knaggit** [comment]
Okay, thanks so far!
