### ISSUE TITLE
JSON content representations

### ISSUE THREAD

**Issue by monobasic** [brocessing/kirby-webpack#45]
Great work on the starterpack!
I noticed, you didn't managed to get JSON content representations working with the dev server either.. any idea whats the problem? I guess it has something to do with dots in urls.. would love to fix this!

**Comment by pqml** [comment]
Yes, it's unfortunately an issue with dots in urls

The only fix for now is to use a proxy instead of the built-in php server.
You can set one from the `proxy` field in `main.config.js`

Kirby 3 will integrates a custom router to use with the php built in server:
https://github.com/k-next/starterkit/blob/master/kirby/router.php
I will try to see if I can implement it with kirby 2 when I have free time

**Comment by pqml** [comment]
[0.9.0 Release](https://github.com/brocessing/kirby-webpack/releases/tag/0.9.0) add support for content representations
