### ISSUE TITLE
Deploying from git

### ISSUE THREAD

**Issue by kybradeck** [brocessing/kirby-webpack#53]
Loving this, thank you for creating it. Has sped up my workflow immensely.

In the past I've used FTP to update my live site, but I'd really love to be able to deploy using git from the command line. I know how to deploy a complete git repo, but is there an easy setup to deploy only the contents of the `www` folder?

**Comment by antoine1000** [comment]
Hi,

Thanks for your feedback. I personally use [git-ftp](https://github.com/git-ftp/git-ftp) to do this kind of thing and since then it worked pretty well.

Concerning your question, if you use git-ftp, you would have to create a `.git-ftp-ignore` file that contains all the folders you want to ignore when transferring your files into your server. It could looks like this:

```
# Ignore these folders and their content
node_modules/*
scripts/*
src/*

# Ignore these files
.babelrc
.editorconfig
.eslintrc
.nvmrc
CHANGELOG.md
kirby.config.json
LICENSE
main.config.js
package.json
package-lock.json
php-error.log
postcss.config.js
README.md
webpack.config.common.js
webpack.config.dev.js
webpack.config.prod.js
yarn.lock
``` 

Hope it answers your question.

Close this issue as it has nothing to do with kirby-webpack itself.
